name = "DataFramesMacros"
uuid = "a3ed533e-75b3-46cb-ad8a-82d33aefb744"
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
DataFrames = "0.21"
DataStructures = "0.17, 0.18"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
